from turtle import *
from time import *
from os import *
t=Turtle()
digi=Turtle()
name=Turtle()
t.speed(.01)
s=getscreen()
digi.ht()
ht()
name.ht()
t.penup()
t.pensize(2)
t.goto(-200,0)
t.pendown()
t.pencolor('black')
t.fillcolor('chartreuse')
t.begin_fill()
for i in range(2):
    t.fd(300)
    t.lt(90)
    t.fd(150)
    t.lt(90)
t.end_fill()
t.penup()
t.goto(-180,20)
t.pendown()
t.pencolor('red')
t.fillcolor('yellow')
t.begin_fill()
for i in range(2):
    t.fd(260)
    t.lt(90)
    t.fd(110)
    t.lt(90)
t.end_fill()
name.penup()
name.goto(-310,160)
name.pendown()
name.pencolor('aquamarine')
name.write('CREATED BY AVIK MAHATO',font=('verdana',25,'bold'))
t.penup()
t.goto(-120,.5)
t.pencolor('Darkblue')
t.write('DIGITAL WATCH',font=('arial',12,'bold'))
digi.ht()
t.ht()
digi.penup()
digi.goto(-171,50)
digi.pendown()
while True:
    samai=localtime()
    dgt=strftime('%H : %M : %S',samai)
    digi.clear()
    digi.write(dgt,font=('arial',35,'bold'))
    sleep(1)